.drone.yml, default.go, default_test.go
Added support for a MAC address type as well as splitting up the
unit tests.  Added validation tests, which indicated some errors
in the unit tests data (e.g. uuid4/5 test data had no version
number in the uuid, and the isbns were bad).
Signed-off-by: Todd Neal <todd@tneal.org>
=> add support for MAC and split/fix tests

default.go
1- The UUID, UUID3, UUID4, and UUID5 validations are self contained in this file without relying on a third party library
2- UUIDs with upper case letters should pass validation now
@casualjim
=> Fixed the uppercase isse for UUIDx validations

.travis.yml, bson.go, bson_test.go, date.go, date_test.go, default.go, default_test.go, duration.go, duration_test.go, time.go, time_test.go
- Make All Types Compatible with mgo.bson;
- Add ObjectId type, wrapping around mgo.bson.ObjectId (once this is merged we need to update go-swagger so that we can add support for this type);
Closes/Fixes:
- https://github.com/go-openapi/strfmt/issues/11
- https://github.com/go-openapi/strfmt/pull/7
- https://github.com/go-swagger/go-swagger/issues/670
Implements one proposal from https://github.com/go-swagger/go-swagger/issues/884
=> Feat mgo compatibility

time.go
The grammar mistake fixed in this PR was found (and by accident fixed as vendor code) by @PaulCapestany.
=> fix grammar mistake found by @PaulCapestany

date.go, time.go
Some SQL drivers do not do deep reflection and result in errors like:
```
"sql: converting Exec argument $2 type: non-Value type strfmt.DateTime returned from Value"
```
This proposed fix simply does an explicit cast to time.Time in these structs.
=> Fixes #13. Adding cast to time.Time for sql.Value calls for non-reflecting drivers

date.go, date_test.go, time.go
Previous PR:https://github.com/go-openapi/strfmt/pull/14 didn't save the time as RFC3339Millis which is expected by the SQL Scan.
=> Fixes #13. Fixing SQL Value to store casted time.Time value as RFC3339Millis

time.go
This basically allows users to set the marshalling format by setting `strfmt.MarshalFormat` to their desired format.
=> Add support for microsecond precision and allow marshalling format to be overridden

bson.go
It appears `bson.ObjectId.UnmarshalText` was removed in favor of `bson.IsObjectIdHex` and `bson.ObjectIdHex`.
=> Fix str->bson function usages

default.go, default_test.go
#26  - When deserializing UUIDs, allow null values in the json. This results
in creating Zero UUID instead of failing deserialization.
Github Issue: https://github.com/go-openapi/strfmt/issues/26
Signed-off-by: Prem Ramanathan <premram@google.com>
=> Handle null uuids when deserializing

date.go, date_test.go
When deserializing, ignore null dates instead of failing.
This makes null values semantically equivalent to missing field
(undefined).
Signed-off-by: Prem Ramanathan <premram@google.com>
=> Handle null dates when deserializing

default.go, default_test.go
This PR introduces a change to the regex which allows for Hostnames to start with a number.
I have added a test for two valid domains which currently pass.
Signed-off-by: James Lamb <jlamb@atlassian.com>
=> Fixes #36 Hostname matching doesn't conform to modern hostname patterns

default.go, default_test.go
Updated PR as my previous one had merge checks because it didn't sync properly 🤦‍♂️ 
This pull request adds support for puny and unicode special character domains to the Hostname validation regex.
* adds tests for the various nesting examples we have been exposed to so far
* adds tests for crazy unicode emoji domain
* adds numerical domains with nesting
=> add unicode (emoji) and puny code domain support to hostname validation

.golangci.yml, default.go, default_test.go
* fixes #42 (simple hostnames, not necessarily FDQNs)
* adds more tests for hostname validations
Validation rules are:
* internationalized (unicode) hostnames are permitted
* for FDQNs, top-level domain (e.g. ".com"), is at least to letters long (no special characters here)
* hostnames may start with a digit [RFC1123]
* special registered names with an underscore ('_') are not allowed in this context
* dashes are permitted, but not at the start or the end of a segment
* long top-level domain names (e.g. example.london) are permitted
* symbol unicode points are permitted (e.g. emoji) (not for top-level domain)
Signed-off-by: Frederic BIDON <fredbi@yahoo.com>
=> Fix hostname validation regexp

bson.go, bson_test.go, date.go, date_test.go, default.go, default_test.go, duration.go, duration_test.go, time.go, time_test.go
Kubernetes has a project called code-generator[0] which generates
DeepCopy methods for API models.
Cilium[1] is using code-generator on top of models generated by
go-swagger, to allow deep copying of API models. Hovewer, code-generator
assumes that every type which is not a basic type in Golang, needs to
have its own DeepCopy and DeepCopyIn methods. It includes also type
extensions which are built on top of basic types just to add methods.
Currently, if code-generator is executed on go-swagger API models which
use types from strfmt, generated DeepCopy methods fail, because strfmt
types do not implement DeepCopy.
This change adds implementations of DeepCopy and DeepCopyInto which will
allow to use go-generator together with go-swagger and strfmt.
[0] …
=> Add DeepCopy and DeepCopyInto methods to all types

bson.go, date.go, default.go, duration.go, time.go
Follow-up to #44.
Fixes: 13e510669953 ("Add DeepCopy and DeepCopyInto methods to all
types")
Signed-off-by: Michal Rostecki <mrostecki@suse.de>
=> Fix typos in comments to DeepCopyInto methods

format.go, format_test.go
=> empty datetime shouldn't be converted to epoch time 

.travis.yml, default_test.go, go.mod, go.sum
fix #38
pborman maintains google's uuid package, and they have a complicated shared history,
but the release notes for pborman/uuid now read
The choice of this package vs the google/uuid package is largely dependent on your
use case. If you want to use UUIDs as keys, used the google/uuid version (a UUID
is an array). Use this package for compatibility, needing to distinguish between
non-set UUID and the zero UUID, prefer byte slices over arrays.
google/uuid is now a dependency of pborman/uuid which is now just a compat wrapper,
so switch to just using google/uuid. Changes are just minor API differences.
Signed-off-by: Justin Cormack <justin.cormack@docker.com>
=> Use google/uuid not pborman/uuid

time.go, time_test.go
ISO8601 states that timestamps without their timezone component are timestamps that are in "local" time. This PR adds support for parsing those types of timestamps.
=> Issue #53: Added support for parsing ISO8601 timestamps that are in local time.

format.go
Hi, we updated an exported function comment based on best practices from [Effective Go](https://golang.org/doc/effective_go.html). It’s admittedly a relatively minor fix up. Does this help you?
=> Fix function comments based on best practices from Effective Go

date.go, date_test.go, time.go, time_test.go
Add methods for Date and DateTime to fulfil interfaces:
- gob.GobEncoder
- gob.GobDecoder
- encoding.BinaryMarshaler
- encoding.BinaryUnmarshaler
During struct serialisation, by using core package "encoding/gob", in case Date or DateTime are used as types for struct fields, error is thrown as result: "type strfmt.Date has no exported fields".
This commits adds those method, by reusing existing ones from time.Time struct.
=> Methods for fulfil methods from encoding and gob packages

time.go
Closes #70
This commit exports the DateTimeFormats variable so that users
can modify the set of formats used by ParseDateTime, as in this
example:
strfmt.DateTimeFormats = append(strfmt.DateTimeFormats, "2006-01-02T15:04Z0700")
Signed-off-by: Phil Adams <phil_adams@us.ibm.com>
=> Export DateTimeFormats variable used by ParseDateTime()

date.go, date_test.go, time.go, time_test.go
Adds support for for `DateTime.Equal(DateTime)` and `Date.Equal(Date)` that uses time's Equal method.
This would simplify our testing flow a lot as the dependency we use (`github.com go-test/deep`) skips checking time.Time's internal properties (exp, loc, ...) by default.
=> Add Equal methods to DateTime and Date

README.md, conv/ulid.go, conv/ulid_test.go, format.go, format_test.go, go.mod, go.sum, ulid.go, ulid_test.go
More details about format:
https://github.com/ulid/spec
It uses binary underlying implementation:
https://github.com/oklog/ulid
Resolves: #77
=> Add support for ULID string format

.golangci.yml, date_test.go, format.go, time_test.go, ulid_test.go
Disable linters and skip lines to lint.
=> Disable linters and skip lines to lint

time.go, time_test.go
This PR adds a new function `IsZero` to the DateTime struct. The goal of this is to satisfy a common interface, IsZeroer, used by go-yaml/yaml marshaller. `IsZero` already exists on the time.Time object, so this does not introduce any novel implementation.
For reference, here is the [documentation
note](https://pkg.go.dev/gopkg.in/yaml.v3#Marshal) on using IsZero by the `(yaml).Marshal` function. If you have a struct generated by swagger that use a proto timestamp, a strfmt.DateTime is used. When you try to marshal this to yaml, _all_ DateTime fields are skipped and excluded.
=> Adds IsZero functionality to DateTime

date.go, format.go, time.go
Interacting with servers that utilize the ISO-8601 Local Time variants in
request and response payloads can configure the request marshaling using
NormalizeTimeForMarshal setting, but don't have a ready method for setting the
local time zone when parsing the response fields.
Keep UTC as the default location, to maintain the previous functionality.
Signed-off-by: Chad Kunde <Kunde21@gmail.com>
=> configure default location for time parsing

default.go, default_test.go, go.mod, go.sum
This PR changes the UUID validation to support either
UUIDs with the expected number of separators or no separator at all.
Under the hood, UUID validation no longer relies on regular expressions
(exported regexp patterns are marked as deprecated) but on
github.com/google/uuid. This brings a significant performance
improvement on validation (~ 15-20 times faster).
Notice that some non-standard UUID schemes as well as UUID v6 and v7
now pass "IsUUID".
* contributes https://github.com/go-swagger/go-swagger/issues/2878
Signed-off-by: Frederic BIDON <fredbi@yahoo.com>
=> fix(uuid): UUID regexes to support all-or-none '-' separator

time.go, time_test.go
This reverts commit b36a4901fcb51dbf4300a5a6b60b4335440aa208.
Fixes https://github.com/go-openapi/strfmt/issues/139
=> Revert "use pointer receivers on the IsZero variants for DateTime"

duration.go, duration_test.go
Only the one the negative one that could be parsed with strconv.ParseDuration were working.
Now all negative durations are working.
Fixes #143
=> Fix negative duration parsing

time.go, time_test.go
* fixed the documentation for NewDateTime() to state explicitly that it does not yield the zero value. This value is checked against IsUNIXZero().
* introduced a new method MakeDateTime() for users who want a zero value that checks against IsZero().
* fixes #141
=> DateTime and the different zero values used.

format.go, format_test.go, go.mod, go.sum
The github.com/mitchellh/mapstructure package is archived and no longer receives updates[^1]. The "blessed" fork[^2] is
github.com/go-viper/mapstructure. The API is the same, so nothing needs to be changed apart from the import path.
[^1]: https://github.com/mitchellh/mapstructure/issues/349
[^2]: https://gist.github.com/mitchellh/90029601268e59a29e64e55bab1c5bdc
=> Migrate to github.com/go-viper/mapstructure/v2

.github/workflows/auto-merge.yml
golang.org updates are not auto merged. The dependency group metadata is empty.
Change to use dep name match.
=> Enabled golang.org dep-bot auto-merge

.golangci.yml, default.go, default_test.go, go.mod, go.sum, time.go
Please select: 🆕 New feature or enhancement|🔧 Bug fix'|📃 Documentation update
=> chore(deps): updated dependencies & relinted

default.go, go.mod, go.sum
github.com/asaskevich/govalidator hasn't evolved in the recent years.
It has proved a useful dependency so far, but now we prefer to duplicate the few lines of codes that we were still using so we are more in control of the validations being carried out.
In particular, we may reduce further the footprint of regexp-based validations.
Please select: 🆕 New feature or enhancement|🔧 Bug fix'|📃 Documentation update
=> chore(deps): removed dependency to govalidator
